[tasks.build]
run = '''
./gen-manifest.sh
'''
sources = [
    'gen-manifest.sh',
    'index.html',
    'sw.template.js',
    'vert/*',
    'bleu/*',
    'noir/*',
    'rouge/*',
    'blanc/*',
    'jaune/*',
    'speciaux/*'
]
outputs = ["manifest.json", "sw.js"]

[tasks.serve]
run = "python3 -m http.server 8000"